=== luenamp/tcm23twg01/Tecnologia5/Tecnologia/xml/xsd.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.samsungGalaxy.org"
xmlns:tns="http://www.samsungGalaxy.org"
elementFormDefault="qualified"
>
<element name="samsungGalaxy">
    <complexType>
      <sequence>
        <element name="caption" type="string" />
        <element name="telemóveis">
          <complexType>
            <sequence>
              <element name="telemóvel" maxOccurs="unbounded">
                <complexType>
                  <sequence>
                    <element name="modelo" type="string" />
                    <element name="caraterísticas">
                      <complexType>
                        <sequence>
                          <element name="opção" maxOccurs="unbounded">
                            <complexType>
                              <sequence>
                                <element name="armazenamento">
                                  <complexType>
                                    <simpleContent>
                                      <extension base="string">
                                        <attribute name="unidade" use="required" />
                                      </extension>
                                    </simpleContent>
                                  </complexType>
                                </element>
                                <element name="preço">
                                  <complexType>
                                    <simpleContent>
                                      <extension base="string">
                                        <attribute name="unidade" use="required" fixed="Euro" />
                                      </extension>
                                    </simpleContent>
                                  </complexType>
                                </element>
                              </sequence>
                            </complexType>
                          </element>
                        </sequence>
                      </complexType>
                    </element>
                  </sequence>
                </complexType>
              </element>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== luenamp/tcm23twg01/tcm23-twg-g01/xml/xml.xml
<?xml version="1.0"?>
<samsungGalaxy xmlns="http://www.samsungGalaxy.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.samsungGalaxy.org xsd.xsd">

  <caption>Em resumo:</caption>
  <telemóveis>
    <telemóvel>
      <modelo>Galaxy S24</modelo>
      <caraterísticas>
        <opção>
          <armazenamento unidade="GB">128</armazenamento>
          <preço unidade="Euro">899</preço>
        </opção>
        <opção>
          <armazenamento unidade="GB">256</armazenamento>
          <preço unidade="Euro">959</preço>
        </opção>
      </caraterísticas>
    </telemóvel>
    <telemóvel>
      <modelo>Galaxy S24+</modelo>
      <caraterísticas>
        <opção>
          <armazenamento unidade="GB">256</armazenamento>
          <preço unidade="Euro">1149</preço>
        </opção>
        <opção>
          <armazenamento unidade="GB">512</armazenamento>
          <preço unidade="Euro">1269</preço>
        </opção>
      </caraterísticas>
    </telemóvel>
    <telemóvel>
      <modelo>Galaxy S24 Ultra</modelo>
      <caraterísticas>
        <opção>
          <armazenamento unidade="GB">256</armazenamento>
          <preço unidade="Euro">1149</preço>
        </opção>
        <opção>
          <armazenamento unidade="GB">512</armazenamento>
          <preço unidade="Euro">1569</preço>
        </opção>
        <opção>
          <armazenamento unidade="TB">1</armazenamento>
          <preço unidade="Euro">1809</preço>
        </opção>
      </caraterísticas>
    </telemóvel>
  </telemóveis>

</samsungGalaxy>
